version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    ports:
      - '9991:9991'
    environment:
      DATABASE_DIRECT_URL: ${DATABASE_DIRECT_URL}
      WG_TOKEN_AUTH_ENDPOINT: ${WG_TOKEN_AUTH_ENDPOINT}
      WG_NODE_HOST: ${WG_NODE_HOST}
      WG_NODE_INTERNAL_PORT: ${WG_NODE_INTERNAL_PORT}
      WG_NODE_URL: ${WG_NODE_URL}
      WG_PUBLIC_NODE_URL: ${WG_PUBLIC_NODE_URL}
      WG_NODE_LOG_LEVEL: ${WG_NODE_LOG_LEVEL}
      WG_SERVER_HOST: ${WG_SERVER_HOST}
      WG_SERVER_PORT: ${WG_SERVER_PORT}
      WG_SERVER_URL: ${WG_SERVER_URL}
      WG_SERVER_LOG_LEVEL: ${WG_SERVER_LOG_LEVEL}
      WG_CSRF_TOKEN_SECRET: ${WG_CSRF_TOKEN_SECRET}
      WG_SECURE_COOKIE_HASH_KEY: ${WG_SECURE_COOKIE_HASH_KEY}
      WG_SECURE_COOKIE_BLOCK_KEY: ${WG_SECURE_COOKIE_BLOCK_KEY}
      MINIO_URL: ${MINIO_URL}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://joseantcordeiro.hopto.org:9991/operations/health/live']
      interval: 30s
      timeout: 20s
      retries: 3