version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    logging:
      driver: 'none'
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb: ~